#!/usr/bin/env bash
#script tyat displays information about asubdomain

digdomain() {
    string=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $string" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
  digdomain "$1" "www"
  digdomain "$1" "lb-01"
  digdomain "$1" "web-01"
  digdomain "$1" "web-02"
elif [ "$#" == 2 ]
then
  digdomain "$1" "$2"
fi
