#!/usr/bin/env bash

# Display usage if less than 4 parameters are passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~

echo "File transferred successfully"

