#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i '/server_name _;/a \        location /redirect_me {\n               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n       }' /etc/nginx/sites-enabled/default
sudo service nginx restart
