#!/usr/bin/env bash
#configure nginx server to have a custom 404 page containing Ceci n'est pas une page
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /404.html;\n        location = /404.html {\n                internal;\n                root /var/www/html;\n        }' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
