#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^frontend.*$/frontend http_frontend\n  bind \*:80\n  mode http\n  default_backend http_backend/' /etc/haproxy/haproxy.cfg
sudo sed -i 's/^backend.*$/backend http_backend\n  mode http\n  balance roundrobin\n  server web-01 web-01:80 check\n  server web-02 web-02:80 check/' /etc/haproxy/haproxy.cfg

# Enable HAProxy service
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
