#!/usr/bin/env bash

# Check if Nginx is running
if ! pgrep nginx > /dev/null ; then
  # Start Nginx
  sudo systemctl start nginx
fi

# Check if Nginx is listening on port 80
if ! sudo netstat -tlnp | grep ':80 .*nginx' > /dev/null ; then
  # Restart Nginx
  sudo systemctl restart nginx
fi
