#!/usr/bin/env bash
#check ngix confg files to find out ifbthe fileshave tye same configutrations
#if not rm default file in the enabled configuration 
#creat asymbolkc link to connect config files 

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
