#!/usr/bin/env bash
#script that creates PID file
#handles signals 
#displays message indefinatly

echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no live me?!" SIGINT
trap "rm -f/var/run/myscript.pid" SIGQUIT
SIGTERM

while ((1))
do
	echo "To infinity and beyound"
	sleep 1
done

