#!/usr/bin/env bash
# script that prints information  about afile
if [ -e "school" ]
then
	echo "school file exist"
if [ -s "school" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ -f "school" ]
then
	echo "school is aregular file"
fi
else
	echo "school file does not exist"
fi
