#!/usr/bin/env bash
#edit etc/host file

#cp etc/host ~/hosts.new
#sed -i 's/127."/127.0.0.2' ~/hosts.new
#echo "8.8.8.8 facebook.com" >> ~/host.new
#cp -f ~hosts.new /etc/hosts
sudo cp /etc/hosts /etc/hosts.bak

# Add the required entries to the /etc/hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
cp -f ~hosts.new /etc/hosts
