#!/usr/bin/env bash
#script that diaplays all active IPv4 IPs on machine its executed on

#get list of all network ip adresses
ip_addresses=$(ifconfig -a | awk '/inet / {print $2}')
#loop through each ip and display IP addresse
for ip in $ip_addresses
do
	#display the IP address
	echo "$ip"
done
