#!/usr/bin/env bash
#run software as another user
# Check that one argument was provided
if [ $# -ne 1 ]; then
        echo "Usage: $0 <username>"
            exit 1
            fi

# Run the whoami command under the specified user
sudo -u "$1" whoami

